# Generated by Django 3.1.7 on 2021-04-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=100)),
                ('Logistics', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'candidate_table',
            },
        ),
    ]
