# Generated by Django 3.1.7 on 2021-04-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product_table',
            },
        ),
    ]
